export { getMockDb } from './app-db'
export { MockDbError, type MockDbCollection, type MockDbErrorCode, type MockDbErrorParams } from './errors'
export { createMockDb } from './mock-db'
export { isStale } from './revisions'
export type { DeliveryStop, MockDb, MockDbOptions, NewRevision, NewTrip, Revision, Trip, TripChanges } from './types'
