import { snapshot } from './desktop-snapshot.mock.js';
import { $, escape, shell, badge, dialog, icon, metricGrid } from './screen-ui.js';
import { roleNames, table, notice, normalize, dateTime, input } from './desktop-ui.js';
const permissions = { 'dashboard.view':'Xem tổng quan','reports.export':'Xuất báo cáo','trips.view':'Xem chuyến','trips.edit':'Sửa chuyến','optimization.run':'Chạy tối ưu','plans.view':'Xem phương án','plans.approve':'Duyệt phương án','fleet.view':'Xem đội xe','fleet.edit':'Sửa đội xe','warehouse.operate':'Thao tác kho','driver.operate':'Thao tác tài xế','users.manage':'Quản lý người dùng','audit.view':'Xem nhật ký' };
// Nhóm sự kiện → tông icon. Bốn nhóm, không tô mỗi hành động một màu.
const actionTone = { trip:['blue','truck'], revision:['violet','review'], optimization:['violet','settings'], loading:['amber','box'], delivery:['green','truck'], vehicle:['amber','wrench'], user:['slate','user'], auth:['slate','user'] };
const actions = { 'trip.created':'Tạo chuyến','trip.updated':'Sửa chuyến','trip.cancelled':'Huỷ chuyến','optimization.saved':'Lưu kết quả tối ưu','revision.approved':'Duyệt phương án','loading.started':'Bắt đầu xếp hàng','loading.completed':'Xếp xong','loading.missing':'Báo thiếu kiện','delivery.started':'Xuất phát giao hàng','delivery.stopCompleted':'Hoàn tất điểm giao','delivery.completed':'Hoàn thành chuyến','delivery.issue':'Báo sự cố giao hàng','vehicle.maintenanceOn':'Đưa xe vào bảo dưỡng','user.created':'Tạo tài khoản','user.locked':'Khoá tài khoản','auth.signedIn':'Đăng nhập' };
const userStatus = u => badge(u.status==='active'?'Đang hoạt động':'Đã khoá', u.status==='active'?'success':'warning');
const initials = name => name.split(' ').slice(-2).map(w => w[0]).join('');
export function users(){
  let selected=snapshot.users[0];
  $('screen-root').innerHTML=shell('users',metricGrid([{ tone:'blue', icon:'users', value:snapshot.users.length, label:'Người dùng', note:'Đang có trong snapshot' },{ tone:'green', icon:'shield', value:Object.keys(roleNames).length, label:'Vai trò', note:'Quản lý theo chức năng nghiệp vụ' },{ tone:'slate', icon:'fleet', value:new Set(snapshot.users.map(u=>u.depot)).size, label:'Kho / chi nhánh', note:[...new Set(snapshot.users.map(u=>u.depot))].join(' · ') }])+`<div class="workbench"><section class="paper"><div class="list-tools"><label class="search">${icon('search',16)}<input id="user-search" placeholder="Tìm tên, email, kho hoặc chi nhánh…" aria-label="Tìm người dùng"></label><label class="tool-field">Vai trò<select id="user-role" aria-label="Lọc vai trò"><option value="all">Mọi vai trò</option>${Object.entries(roleNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><button class="button secondary" id="permissions-open">Xem ma trận quyền</button></div><div id="users-table"></div></section><aside class="editor-paper"><div id="user-inspector"></div></aside></div>${dialog('permissions-dialog','Ma trận quyền theo vai trò',table(['Quyền',...Object.values(roleNames)],snapshot.permissions.map(p=>`<tr><td>${permissions[p]}</td>${Object.keys(roleNames).map(role=>`<td><span aria-label="${snapshot.roles[role].includes(p)?'Có quyền':'Không có quyền'}">${snapshot.roles[role].includes(p)?'✓':'—'}</span></td>`).join('')}</tr>`).join(''))+notice('Phân quyền FE giả lập. Backend phải kiểm lại; prototype chỉ trình bày ma trận, không cấp quyền.'))}`);
  function inspector(){const u=selected;$('user-inspector').innerHTML=`<div class="inspector-head"><span class="large-avatar">${initials(u.fullName)}</span><div><h2>${u.fullName}</h2><p class="quiet-note">${u.email}</p>${userStatus(u)}</div></div><h3 class="inspector-section">Thông tin cá nhân</h3><dl class="definition-list"><div><dt>Vai trò</dt><dd>${roleNames[u.role]}</dd></div><div><dt>Kho / chi nhánh</dt><dd>${u.depot}</dd></div><div><dt>Điện thoại</dt><dd>${u.phone}</dd></div><div><dt>Hoạt động gần nhất</dt><dd>${u.lastActiveAt?dateTime(u.lastActiveAt):'Chưa đăng nhập'}</dd></div></dl><h3 class="inspector-section">Công việc được phép</h3><p class="quiet-note">Danh sách quyền của vai trò này. Đây là nhãn, không phải nút bấm.</p><ul class="permission-list">${snapshot.roles[u.role].map(p=>`<li>${permissions[p]}</li>`).join('')}</ul><a class="button secondary" href="/nguoi-dung">Quản lý trong FE hiện tại ↗</a>`;}
  function render(){const rows=snapshot.users.filter(u=>normalize(u.fullName+' '+u.email+' '+u.depot).includes(normalize($('user-search').value))&&($('user-role').value==='all'||u.role===$('user-role').value));$('users-table').innerHTML=table(['Người dùng','Vai trò','Kho / chi nhánh','Trạng thái'],rows.map(u=>`<tr class="${u.id===selected.id?'selected-row':''}"><td><button class="cell-lead" data-user="${u.id}"><span class="cell-thumb ${u.status==='active'?'blue':'amber'}">${initials(u.fullName)}</span><span class="row-title">${u.fullName}<small>${u.email}</small></span></button></td><td><span class="role-chip">${roleNames[u.role]}</span></td><td>${u.depot}</td><td>${userStatus(u)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Không tìm thấy người dùng.</td></tr>');}
  $('user-search').oninput=render;$('user-role').onchange=render;$('users-table').onclick=e=>{const b=e.target.closest('[data-user]');if(!b)return;selected=snapshot.users.find(u=>u.id===b.dataset.user);render();inspector();};$('permissions-open').onclick=()=> $('permissions-dialog').showModal();render();inspector();
}
export function audit(){
  let page=0; const events=snapshot.events.toReversed();
  const latestDay=events[0].at.slice(0,10);
  $('screen-root').innerHTML=shell('audit',metricGrid([{ tone:'blue', icon:'log', value:events.length, label:'Sự kiện trong snapshot', note:'Lịch sử mẫu neo ngày 22/09/2026' },{ tone:'slate', icon:'calendar', value:events.filter(e=>e.at.slice(0,10)===latestDay).length, label:`Sự kiện ngày ${latestDay.split('-').reverse().join('/')}`, note:'Ngày gần nhất có ghi nhận' },{ tone:'slate', icon:'clock', value:dateTime(events[0].at).split(' ')[0], label:'Ghi nhận gần nhất', note:'Chỉ đọc · không phát sinh từ prototype' }])+`<section class="paper"><div class="list-tools"><label class="search">${icon('search',16)}<input id="audit-search" placeholder="Tìm mã chuyến hoặc người thực hiện…" aria-label="Tìm nhật ký"></label><label class="tool-field">Nhóm<select id="audit-group" aria-label="Lọc nhóm sự kiện"><option value="all">Mọi nhóm</option><option value="trip">Chuyến hàng</option><option value="loading">Xếp hàng</option><option value="delivery">Giao hàng</option><option value="user">Tài khoản</option><option value="revision">Duyệt phương án</option></select></label></div><div id="audit-table"></div><div class="pagination"><span id="audit-count" aria-live="polite"></span><button id="audit-prev" class="button secondary">← Trước</button><button id="audit-next" class="button secondary">Sau →</button></div></section>${notice('115 sự kiện có trong seed, neo ngày 22/09/2026. Đây là lịch sử mẫu, không phải nhật ký mới phát sinh từ các prototype.')} ${dialog('audit-detail','Chi tiết sự kiện','<div id="audit-detail-body"></div>')}`, badge('Chỉ đọc','neutral'));
  const actor=e=>snapshot.users.find(u=>u.id===e.actorId)?.fullName??'Hệ thống';
  const roleOf=e=>{const u=snapshot.users.find(u=>u.id===e.actorId);return u?roleNames[u.role]:'Hệ thống';};
  function render(){const filtered=events.filter(e=>normalize(e.target.id+' '+actor(e)+' '+actions[e.action]).includes(normalize($('audit-search').value))&&($('audit-group').value==='all'||e.action.split('.')[0]===$('audit-group').value));const rows=filtered.slice(page*15,page*15+15);$('audit-table').innerHTML=table(['Thời gian','Người thực hiện','Hành động','Đối tượng'],rows.map(e=>`<tr><td class="time-cell"><strong>${dateTime(e.at).split(' ')[0]}</strong><small>${dateTime(e.at).split(' ').slice(1).join(' ')}</small></td><td><span class="row-title">${actor(e)}<small>${roleOf(e)}</small></span></td><td><span class="cell-lead"><span class="cell-thumb ${actionTone[e.action.split('.')[0]]?.[0]??'slate'}">${icon(actionTone[e.action.split('.')[0]]?.[1]??'log',16)}</span><span class="row-title">${actions[e.action]??e.action}</span></span></td><td><button class="row-title mono" data-event="${e.id}">${e.target.id}<small>Xem chi tiết →</small></button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Không có sự kiện phù hợp.</td></tr>');$('audit-count').textContent=`${filtered.length? page*15+1:0}–${Math.min(page*15+15,filtered.length)} / ${filtered.length} sự kiện`;$('audit-prev').disabled=page===0;$('audit-next').disabled=(page+1)*15>=filtered.length;}
  $('audit-search').oninput=$('audit-group').onchange=()=>{page=0;render();};$('audit-prev').onclick=()=>{page--;render();};$('audit-next').onclick=()=>{page++;render();};$('audit-table').onclick=e=>{const b=e.target.closest('[data-event]');if(!b)return;const row=events.find(r=>r.id===b.dataset.event);$('audit-detail-body').innerHTML=`<p>${actions[row.action]} · ${actor(row)}</p><p>${dateTime(row.at)} · <span class="mono">${row.target.id}</span></p><h3>Dữ liệu ghi nhận từ snapshot</h3><pre class="event-json">${escape(JSON.stringify(row.params,null,2))}</pre>${notice('Tên trường kỹ thuật được giữ trong phần kiểm tra dữ liệu dành cho quản trị.')}`;$('audit-detail').showModal();};render();
}
export function profile(){
  const u=snapshot.users[0];
  $('screen-root').innerHTML=shell('profile',`<div class="profile-layout"><aside class="profile-card"><span class="large-avatar">TT</span><h2>${u.fullName}</h2><p>${u.email}</p>${badge(roleNames[u.role],'info')}<hr><p>${u.depot}</p><p class="quiet-note">Vai trò và email do quản trị quản lý.</p></aside><section class="paper form-paper"><h2>Thông tin cá nhân</h2><p class="quiet-note">Thử thay đổi để xem bước kiểm tra. Không cập nhật tài khoản đang đăng nhập.</p><form id="profile-form"><div class="field-grid">${input('Họ và tên','fullName',u.fullName,'required maxlength="80"')}${input('Điện thoại','phone',u.phone,'required inputmode="tel"')}</div><p id="profile-result" class="form-result" role="status"></p><button class="button primary">Kiểm tra thông tin</button></form><div class="security-section"><h2>Bảo mật tài khoản</h2><p>Đổi mật khẩu yêu cầu xác nhận mật khẩu hiện tại trong hệ thống.</p><a class="button secondary" href="/ho-so">Mở hồ sơ hiện tại để đổi mật khẩu ↗</a></div><div class="security-section"><h2>Tùy chọn hiển thị bản mẫu</h2><label class="setting-row"><div><strong>Giảm hiệu ứng kính</strong><p>Giữ nền rõ hơn trong bộ phác thảo desktop.</p></div><input type="checkbox" id="solid-preference"></label></div></section></div>`);
  $('profile-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const valid=/^0\d{9}$/.test(d.get('phone').replace(/\s/g,''))&&d.get('fullName').trim().length>0;e.target.elements.phone.setAttribute('aria-invalid',String(!valid));$('profile-result').textContent=valid?'Thông tin đúng định dạng. Chưa lưu tài khoản.':'Nhập họ tên và số điện thoại 10 chữ số, bắt đầu bằng 0.';};
  $('solid-preference').checked=sessionStorage.getItem('loadmaster-v2-solid')==='1';$('solid-preference').onchange=e=>{sessionStorage.setItem('loadmaster-v2-solid',e.target.checked?'1':'0');document.body.classList.toggle('solid-desktop',e.target.checked);};
}
