import { packages, stops } from './trip-detail.mock.js';
import { $, fmt, escape, shell, dialog, link } from './screen-ui.js';
import { table, notice, normalize } from './desktop-ui.js';
export function cargo() {
  let rows = structuredClone(packages), selected = rows[0].id;
  $('screen-root').innerHTML = shell('cargo', `<div class="workspace-intro"><div><span class="mono">TRIP-2026-0914</span><p>Kiểm tra dữ liệu trước khi chạy phương án. Chỉnh sửa ở đây chỉ áp vào bản phác thảo.</p></div>${link('Thiết lập tối ưu →','optimize')}</div><div class="workbench"><section class="paper"><div class="list-tools"><input id="cargo-search" placeholder="Tìm tên hoặc mã kiện…" aria-label="Tìm kiện"><button class="button secondary" id="import-open">Nhập danh sách mẫu</button><span id="cargo-total" class="quiet-count" aria-live="polite"></span></div><div id="cargo-table"></div>${notice('Chọn một dòng để sửa. Đơn vị cm / kg; thay đổi không ghi vào phương án đã duyệt.')}</section><aside class="editor-paper"><div class="section-heading"><h2>Thông tin kiện</h2><span class="badge info">Bản nháp</span></div><form id="cargo-form"><div id="cargo-fields"></div><p id="cargo-message" role="status" class="form-result"></p><button class="button primary">Áp dụng vào bản mẫu</button></form></aside></div>${dialog('import-dialog','Kiểm tra danh sách trước khi nhập',`<p>Dán dữ liệu phân cách bằng dấu chấm phẩy; đây là bước thử bố cục kiểm lỗi trước khi nối luồng Excel.</p><label class="field">Mỗi dòng: mã; tên; số lượng; điểm giao<textarea id="import-text" rows="5" spellcheck="false"></textarea></label><div class="dialog-actions"><button id="import-example" class="button secondary">Điền mẫu có lỗi</button><button id="import-check" class="button secondary">Kiểm tra dữ liệu</button></div><div id="import-result" aria-live="polite"></div>${notice('Chưa nhập vào chuyến. Muốn nhập .xlsx thật, dùng chức năng hiện có trong FE.')}<a class="button secondary" href="/chuyen/TRIP-2026-0914/sua">Mở màn nhập Excel hiện tại ↗</a>`)}`);
  function renderTable() {
    const visible = rows.filter(p => normalize(p.id+' '+p.name).includes(normalize($('cargo-search').value)));
    $('cargo-total').textContent = `${rows.length} loại · ${rows.reduce((s,p)=>s+p.quantity,0)} kiện`;
    $('cargo-table').innerHTML = table(['Kiện hàng','Điểm','SL','D × R × C (cm)','Kg/kiện'], visible.map(p => `<tr ${p.id===selected?'class="selected-row"':''}><td><button class="row-title" data-cargo="${p.id}">${escape(p.name)}<small class="mono">${p.id}</small></button></td><td><span class="stop-dot stop-${p.stop}">${p.stop}</span></td><td class="num">${p.quantity}</td><td class="num">${p.size.join(' × ')}</td><td class="num">${fmt.format(p.kg)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">Không có kiện khớp tìm kiếm.</td></tr>');
  }
  function editor() { const p=rows.find(p=>p.id===selected); $('cargo-fields').innerHTML = `<p class="mono editor-code">${p.id}</p><label class="field">Tên kiện<input name="name" value="${escape(p.name)}" required maxlength="120"></label><div class="field-grid"><label class="field">Số lượng<input name="quantity" type="number" min="1" max="1000" step="1" value="${p.quantity}" required></label><label class="field">Kg / kiện<input name="kg" type="number" min="0.01" step="0.01" value="${p.kg}" required></label></div><fieldset class="dimensions-field"><legend>Kích thước (cm)</legend>${['Dài','Rộng','Cao'].map((s,i)=>`<label>${s}<input type="number" min="0.1" step="0.1" name="size${i}" value="${p.size[i]}" required></label>`).join('')}</fieldset><label class="field">Điểm giao<select name="stop">${stops.map((s,i)=>`<option value="${i+1}" ${p.stop===i+1?'selected':''}>${i+1} · ${s}</option>`).join('')}</select></label><label class="check-line"><input type="checkbox" name="fragile" ${p.fragile?'checked':''}>Hàng dễ vỡ</label><label class="check-line"><input type="checkbox" name="upright" ${p.upright?'checked':''}>Giữ đứng khi xếp</label>`; $('cargo-message').textContent=''; }
  $('cargo-search').oninput=renderTable;
  $('cargo-table').onclick=e=>{const b=e.target.closest('[data-cargo]');if(!b)return;selected=b.dataset.cargo;renderTable();editor();};
  $('cargo-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target); rows=rows.map(p=>p.id===selected?{...p,name:d.get('name').trim(),quantity:Number(d.get('quantity')),kg:Number(d.get('kg')),size:[0,1,2].map(i=>Number(d.get('size'+i))),stop:Number(d.get('stop')),fragile:d.has('fragile'),upright:d.has('upright')}:p);renderTable();$('cargo-message').textContent='Đã áp dụng trong bản mẫu. Tải lại trang sẽ khôi phục snapshot.';};
  $('import-open').onclick=()=> $('import-dialog').showModal();
  $('import-example').onclick=()=>{$('import-text').value='PKG-001;Thùng nhựa;38;1\nPKG-001;Thùng sữa;0;2\nPKG-007;Ly thuỷ tinh;11;9';};
  $('import-check').onclick=()=>{const lines=$('import-text').value.trim().split('\n').filter(Boolean),ids=new Set();const result=lines.map((line,i)=>{const [id,name,qty,stop]=line.split(';').map(s=>s.trim());const errors=[];if(!id||!name)errors.push('thiếu mã hoặc tên');if(ids.has(id))errors.push('trùng mã trong danh sách');if(rows.some(p=>p.id===id))errors.push('mã đã có trong chuyến');ids.add(id);if(!Number.isInteger(Number(qty))||Number(qty)<1)errors.push('số lượng phải là số nguyên dương');if(!Number.isInteger(Number(stop))||Number(stop)<1||Number(stop)>4)errors.push('điểm giao phải từ 1 đến 4');return `<li><strong>Dòng ${i+1} · ${escape(id||'Chưa có mã')}</strong><span>${errors.length?errors.join(' · '):'Đủ 4 trường; còn cần bổ sung kích thước và yêu cầu xếp.'}</span></li>`;});$('import-result').innerHTML=lines.length?`<ul class="import-issues">${result.join('')}</ul>`:'<p class="form-result">Chưa có dữ liệu để kiểm tra.</p>';};
  renderTable();editor();
}
