import { positionSheet,showPosition } from './mobile-position.js';
import { placements } from './mobile-placements.mock.js';
import { stops } from './trip-detail.mock.js';
import { $,role,link,icon,button,tag,shell,sheet,fmt } from './mobile-ui.js';
export function scene(){
 const params=new URL(location.href).searchParams;const stop=Math.max(1,Math.min(4,Number(params.get('stop'))||1));
 const sequence=placements.filter(p=>role==='warehouse'||p.stop===stop).toSorted((a,b)=>role==='warehouse'?a.step-b.step:a.unloadingOrder-b.unloadingOrder);
 let index=Math.max(0,sequence.findIndex(p=>p.id===params.get('package'))),timer=null,warning=params.get('warning')==='1';
 $('mobile-root').innerHTML=shell('scene',`<section class="m-scene-stage"><div class="m-scene-top"><div><span class="scene-mode">${role==='driver'?'Dỡ hàng':'Xếp hàng'} <i>•</i> Chỉ xem</span><strong id="scene-stop-name"></strong></div><button id="scene-options" class="glass-icon" aria-label="Tùy chọn hiển thị">${icon('layers')}</button></div><img class="m-truck-image" src="./mobile-engine-overview.png" alt="Ảnh tổng quan xe và 132 kiện, chụp từ engine LoadMaster"><div class="m-scene-footnote"><span>Ảnh tổng quan cố định</span><span>MOCK RESULT</span></div><div id="m-legend" class="m-legend" hidden>${stops.map((s,i)=>`<span><i class="stop-${i+1}">${i+1}</i>Điểm ${i+1}</span>`).join('')}</div></section><section class="m-cargo-sheet"><div class="sheet-handle" aria-hidden="true"></div><div class="m-step-meta"><span id="m-step-label"></span><span class="m-step-small">Hướng dẫn mẫu</span></div><div class="m-selected-cargo"><span class="cargo-icon">${icon('box')}</span><div><h2 id="m-package-id" class="mono"></h2><p id="m-package-name"></p></div><button id="package-open" class="icon-button" aria-label="Chi tiết kiện">${icon('right')}</button></div><p id="m-package-size" class="m-size"></p><button id="position-open" class="m-position-button">${icon('map')}Vị trí từ trên xuống${icon('right')}</button><div id="m-advisory" class="m-advisory" hidden>${icon('alert')}<div><strong>Kiểm tra lối dỡ</strong><p>Mẫu cảnh báo: có kiện có thể cản đường. Cần đối chiếu trong 3D.</p></div></div><div class="m-playback"><button id="step-prev" class="icon-button" aria-label="Kiện trước">${icon('back')}</button><button id="step-play" class="m-play" aria-label="Phát hướng dẫn mẫu">${icon('play')}</button><button id="step-next" class="icon-button" aria-label="Kiện tiếp theo">${icon('right')}</button><div><input id="step-range" type="range" min="0" max="${sequence.length-1}" value="0" aria-label="Bước hướng dẫn"><small id="step-count"></small></div></div><a id="scene-scan" class="m-button primary">${icon('scan')}Đối chiếu mã kiện</a><a class="m-engine-link" href="${role==='driver'?'/tai-xe/diem-giao?chuyen=TRIP-2026-0914':'/kho?chuyen=TRIP-2026-0914'}">Mở mô hình 3D tương tác hiện tại ↗</a></section>`,'',{dark:true,back:role==='driver'?'stop':'home',backExtra:`&stop=${stop}`})+sheet('scene-options-sheet','Hiển thị hướng dẫn',`<label class="m-toggle"><span>Chú giải điểm giao<small>Số điểm luôn đi cùng màu</small></span><input id="show-legend" type="checkbox"></label><label class="m-toggle"><span>Cảnh cảnh báo minh hoạ<small>Duyệt cách trình bày, không phải kết quả kiểm tra phương án</small></span><input id="show-warning" type="checkbox" ${warning?'checked':''}></label><p class="m-source">Phát hướng dẫn đổi thông tin theo loadingOrder/unloadingOrder từ snapshot. Ảnh xe không đổi theo bước; chưa có animation dỡ hàng trong phác thảo này.</p>`)+sheet('package-sheet','Kiện cần đối chiếu','<div id="package-details"></div>')+positionSheet();
 function pause(){if(timer)clearInterval(timer);timer=null;$('step-play').innerHTML=icon('play');$('step-play').setAttribute('aria-label','Phát hướng dẫn mẫu');}
 function render(){const p=sequence[index];$('scene-stop-name').textContent=`Điểm ${p.stop} · ${stops[p.stop-1]}`;$('m-step-label').textContent=`${role==='warehouse'?'Bước xếp':'Kiện tại điểm'} ${index+1} / ${sequence.length}`;$('m-package-id').textContent=p.id;$('m-package-name').textContent=p.name;$('m-package-size').textContent=`${p.size.join(' × ')} cm · ${fmt.format(p.kg)} kg`;$('step-count').textContent=`${index+1} / ${sequence.length}`;$('step-range').value=String(index);$('step-prev').disabled=index===0;$('step-next').disabled=index===sequence.length-1;$('scene-scan').href=link('scan',`&package=${p.id}&stop=${p.stop}`);$('m-advisory').hidden=!warning;if(index===sequence.length-1)pause();}
 $('step-prev').onclick=()=>{pause();index=Math.max(0,index-1);render();};$('step-next').onclick=()=>{pause();index=Math.min(sequence.length-1,index+1);render();};$('step-range').oninput=e=>{pause();index=Number(e.target.value);render();};$('step-play').onclick=()=>{if(timer){pause();return;}if(index===sequence.length-1)index=0;render();$('step-play').innerHTML=icon('pause');$('step-play').setAttribute('aria-label','Dừng hướng dẫn mẫu');timer=setInterval(()=>{index++;render();},1800);};
 $('scene-options').onclick=()=>{pause();$('scene-options-sheet').showModal();};$('show-legend').onchange=e=>{$('m-legend').hidden=!e.target.checked;};$('show-warning').onchange=e=>{warning=e.target.checked;render();};$('package-open').onclick=()=>{pause();const p=sequence[index];$('package-details').innerHTML=`<div class="m-sheet-package"><span class="cargo-icon">${icon('box')}</span><h3 class="mono">${p.id}</h3><p>${p.name}</p>${tag(`Điểm ${p.stop}`)}${p.fragile?tag('Dễ vỡ','warning'):''}<dl><div><dt>Kích thước sau đặt</dt><dd>${p.size.join(' × ')} cm</dd></div><div><dt>Khối lượng</dt><dd>${fmt.format(p.kg)} kg</dd></div><div><dt>Từ vách trước / trái / sàn</dt><dd>${[p.position.x,p.position.y,p.position.z].map(v=>fmt.format(v)).join(' / ')} cm</dd></div></dl><p class="m-source">Vị trí theo snapshot phương án. Mobile không sửa vị trí hoặc xoay kiện.</p>${button('Báo sự cố kiện này','issue',false,`&package=${p.id}&stop=${p.stop}`)}</div>`;$('package-sheet').showModal();};
 $('position-open').onclick=()=>{pause();showPosition(sequence[index]);};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',pause);render();
}



