import { packages,stops,addresses } from './trip-detail.mock.js';
import { doneCount } from './mobile-flow.js';
import { $,link,icon,button,tag,shell,sheet,fmt } from './mobile-ui.js';
export function stop(){
 let index=Math.max(1,Math.min(4,Number(new URL(location.href).searchParams.get('stop'))||1));
 $('mobile-root').innerHTML=shell('stop',`<div class="m-content"><label class="m-field">Điểm giao<select id="m-stop">${stops.map((s,i)=>`<option value="${i+1}">${i+1} / 4 · ${s}</option>`).join('')}</select></label><section id="m-stop-detail" class="m-stop-focus"></section><div class="m-section-title"><h2>Hàng tại điểm này</h2><span id="m-stop-count"></span></div><div id="m-stop-cargo"></div><button class="m-link-row" id="route-open">${icon('map')}<span>Xem đủ 4 điểm giao</span>${icon('right')}</button><p class="m-source">Đây là thứ tự điểm giao trong phương án mẫu, chưa phải tiến độ giao thực tế.</p></div>`,button('Xem vị trí & hướng dẫn dỡ','scene',true,`&stop=${index}`))+sheet('route-sheet','Thứ tự điểm giao',`<ol class="m-route">${stops.map((s,i)=>`<li><span class="stop-dot stop-${i+1}">${i+1}</span><a href="${link('stop',`&stop=${i+1}`)}"><strong>${s}</strong><small>${addresses[i]}</small></a></li>`).join('')}</ol>`);
 function render(){const rows=packages.filter(p=>p.stop===index);$('m-stop-detail').innerHTML=`<span class="stop-dot stop-${index}">${index}</span><span class="m-eyebrow">Điểm đang xem / ${index} trên 4</span><h2>${stops[index-1]}</h2><p>${addresses[index-1]}</p><div class="m-stop-session"><strong>${doneCount(index)} kiện đã xác nhận</strong><span>Trong phiên mẫu · chưa đồng bộ</span></div><div class="m-address-actions"><a class="m-button secondary" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stops[index-1]+', '+addresses[index-1])}">${icon('map')}Mở bản đồ</a>${button('Báo sự cố','issue',false,`&stop=${index}`)}</div>`;$('m-stop-count').textContent=`${rows.reduce((n,p)=>n+p.quantity,0)} kiện`;$('m-stop-cargo').innerHTML=rows.map(p=>`<div class="m-cargo-line"><span class="cargo-icon">${icon('box')}</span><div><h3>${p.name}</h3><p>${p.quantity} kiện · ${fmt.format(p.kg)} kg/kiện</p>${tag(p.fragile?'Dễ vỡ':p.upright?'Giữ đứng':'Được đổi hướng',p.fragile?'warning':'neutral')}</div></div>`).join('');document.querySelector('.m-action-footer a').href=link('scene',`&stop=${index}`);}
 $('m-stop').value=String(index);$('m-stop').onchange=e=>{index=Number(e.target.value);render();};$('route-open').onclick=()=> $('route-sheet').showModal();render();
}

