import { $,role,link,icon,button,tag,shell,sheet,readQueue } from './mobile-ui.js';
import { resetFlow } from './mobile-flow.js';

export function applyPreferences(){
 for(const [key,cls] of [['solid','m-solid'],['motion','m-reduce-motion'],['large','m-large-text']])document.body.classList.toggle(cls,sessionStorage.getItem(`lm-mobile-${key}`)==='1');
}

export function login(){
 const expired=new URL(location.href).searchParams.get('expired')==='1';
 $('mobile-root').innerHTML=shell('login',`<div class="m-content m-login"><div class="m-login-intro"><span class="m-access-label">Tài xế & nhân viên kho</span><h1>Đăng nhập công việc</h1><p>Dùng tài khoản được doanh nghiệp cấp.</p></div>${expired?'<div class="m-account-notice" role="status">Phiên đã hết hạn. Đăng nhập lại để tiếp tục. Thao tác chờ gửi trong tab vẫn được giữ.</div>':''}<form id="m-login-form"><label class="m-field">Email<input type="email" id="login-email" autocomplete="username" inputmode="email" autocapitalize="none" spellcheck="false" required placeholder="ten@doanhnghiep.vn" aria-describedby="login-error"></label><label class="m-field">Mật khẩu<span class="m-password-field"><input type="password" id="login-password" autocomplete="current-password" required aria-describedby="login-error"><button type="button" id="password-show" aria-label="Hiện mật khẩu" aria-pressed="false">Hiện</button></span></label><div class="m-login-help"><a href="${link('access')}">Không đăng nhập được?</a></div><p id="login-error" class="m-feedback invalid" role="alert" hidden></p><button class="m-button primary" id="login-submit">Đăng nhập bản mẫu</button></form><details class="m-demo-access" open><summary>Dùng tài khoản để duyệt thiết kế</summary><p>Mật khẩu mẫu: <code>loadmaster</code>. Không nhập mật khẩu thật.</p><div><button class="m-button secondary" data-demo="driver">${icon('truck')}Tài xế</button><button class="m-button secondary" data-demo="warehouse">${icon('box')}Nhân viên kho</button></div></details><div class="m-access-foot">${icon('check')}<p>Vào đúng màn theo vai trò tài khoản.<br><span>Đây là đăng nhập mô phỏng, không xác thực máy chủ.</span></p></div></div>`,'',{back:'home'});
 $('password-show').onclick=()=>{const show=$('login-password').type==='password';$('login-password').type=show?'text':'password';$('password-show').textContent=show?'Ẩn':'Hiện';$('password-show').setAttribute('aria-label',show?'Ẩn mật khẩu':'Hiện mật khẩu');$('password-show').setAttribute('aria-pressed',String(show));};
 const clear=()=>{$('login-error').hidden=true;for(const id of ['login-email','login-password'])$(id).removeAttribute('aria-invalid');};
 for(const id of ['login-email','login-password'])$(id).oninput=clear;
 document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{clear();$('login-email').value=b.dataset.demo==='driver'?'taixe@loadmaster.vn':'kho@loadmaster.vn';$('login-password').value='loadmaster';$('login-submit').focus();});
 $('m-login-form').onsubmit=e=>{e.preventDefault();const email=$('login-email').value.trim().toLowerCase(),password=$('login-password').value;const assigned=email==='taixe@loadmaster.vn'?'driver':email==='kho@loadmaster.vn'?'warehouse':null;
  if(!assigned||password!=='loadmaster'){$('login-error').hidden=false;$('login-error').textContent='Email hoặc mật khẩu chưa đúng. Dùng tài khoản mẫu phía dưới để thử.';for(const id of ['login-email','login-password'])$(id).setAttribute('aria-invalid','true');$('login-email').focus();return;}
  // Store only demo role; credentials are never persisted or sent.
  sessionStorage.setItem('lm-mobile-demo-session',assigned);$('login-password').value='';location.href=`./mobile.html?view=home&role=${assigned}`;
 };
}

export function settings(){
 $('mobile-root').innerHTML=shell('settings',`<div class="m-content"><div class="m-settings-intro"><h2>Hiển thị theo cách bạn dùng</h2><p>Áp dụng ngay trong bản mẫu này.</p></div><section class="m-settings-group"><h3>Khả năng đọc</h3><label class="m-toggle"><span>Nền rõ ngoài trời<small>Giảm kính và phản sáng; giữ nguyên màu điểm giao.</small></span><input id="m-solid" type="checkbox"></label><label class="m-toggle"><span>Chữ nội dung lớn hơn<small>Tăng chữ hướng dẫn, biểu mẫu và nút. Không thu nhỏ để ép vừa màn.</small></span><input id="m-large" type="checkbox"></label></section><section class="m-settings-group"><h3>Chuyển động</h3><label class="m-toggle"><span>Giảm chuyển động<small>Tắt chuyển cảnh panel. Không tự tắt trình phát khi bạn chủ động bấm.</small></span><input id="m-motion" type="checkbox"></label><p class="m-source">Luôn tôn trọng cài đặt giảm chuyển động của thiết bị.</p></section><section class="m-settings-group"><h3>Dữ liệu & thiết bị</h3><a class="m-link-row" href="${link('queue')}">${icon('sync')}<span>Thao tác chờ gửi<small>${readQueue().filter(q=>q.status!=='sent').length} mục trong phiên mẫu</small></span>${icon('right')}</a><button class="m-link-row" id="permissions-open">${icon('camera')}<span>Camera & ảnh<small>Cách quyền sẽ được dùng trong app</small></span>${icon('right')}</button><a class="m-link-row" href="${link('about')}">${icon('box')}<span>Thông tin bản mẫu</span>${icon('right')}</a></section><p class="m-source">Tùy chọn lưu trong tab hiện tại. App Flutter sẽ cần lưu cài đặt trên thiết bị.</p></div>`,'',{back:'profile'})+sheet('permissions-sheet','Camera & ảnh',`<div class="m-help-section"><h3>Quét mã kiện</h3><p>App sẽ xin quyền camera khi mở quét mã. Nếu từ chối, vẫn có ô nhập mã và máy quét dạng bàn phím.</p><h3>Ảnh khi báo sự cố</h3><p>Chỉ chọn hoặc chụp ảnh khi cần báo sự cố. Bản web này đã mở được trình chọn ảnh; chưa xin quyền camera hoặc tải ảnh lên.</p><p class="m-source">Đây là hướng dẫn thiết kế cho Flutter, không phải trạng thái quyền của điện thoại hiện tại.</p></div>`);
 for(const [id,key] of [['m-solid','solid'],['m-large','large'],['m-motion','motion']]){$(id).checked=sessionStorage.getItem(`lm-mobile-${key}`)==='1';$(id).onchange=e=>{sessionStorage.setItem(`lm-mobile-${key}`,e.target.checked?'1':'0');applyPreferences();};}
 $('permissions-open').onclick=()=>$('permissions-sheet').showModal();
}

export function access(){
 $('mobile-root').innerHTML=shell('access',`<div class="m-content"><div class="m-settings-intro"><span class="cargo-icon">${icon('user')}</span><h2>Cần hỗ trợ tài khoản?</h2><p>Tài khoản do doanh nghiệp quản lý. Không cần tạo tài khoản mới.</p></div><ol class="m-help-steps"><li><strong>Kiểm tra thông tin đăng nhập</strong><p>Email đúng doanh nghiệp, không có khoảng trắng thừa. Dùng nút Hiện để kiểm tra mật khẩu.</p></li><li><strong>Liên hệ người cấp tài khoản</strong><p>Nhờ quản trị viên kiểm tra tài khoản bị khoá hoặc cấp lại mật khẩu. Không gửi mật khẩu hiện tại.</p></li></ol><div class="m-help-section"><h3>Nội dung có thể gửi quản trị viên</h3><label class="m-field">Mẫu yêu cầu hỗ trợ<textarea id="support-copy" readonly>Tôi không đăng nhập được LoadMaster. Nhờ kiểm tra trạng thái tài khoản hoặc hướng dẫn cấp lại mật khẩu. Email của tôi: …</textarea></label><button class="m-button secondary" id="copy-help">Sao chép nội dung</button><p id="copy-result" role="status" class="m-source"></p></div><p class="m-source">Bản mẫu không gửi email hoặc đặt lại mật khẩu. Thông tin liên hệ hỗ trợ cần doanh nghiệp cung cấp khi pilot.</p></div>`,button('Quay lại đăng nhập','login',true),{back:'login'});
 $('copy-help').onclick=async()=>{try{await navigator.clipboard.writeText($('support-copy').value);$('copy-result').textContent='Đã sao chép. Bạn tự gửi cho người quản trị tài khoản.';}catch{$('support-copy').focus();$('support-copy').select();$('copy-result').textContent='Chọn nội dung trong ô để sao chép thủ công.';}};
}

export function about(){
 $('mobile-root').innerHTML=shell('about',`<div class="m-content"><div class="m-about-brand"><span class="m-logo">L</span><h2>LoadMaster</h2><p>Mobile 03 · Bản thiết kế tương tác</p>${tag('MOCK RESULT')}</div><dl class="m-about-details"><div><dt>Dành cho</dt><dd>Tài xế & nhân viên kho</dd></div><div><dt>Nền tảng dự kiến</dt><dd>Flutter · Android trước</dd></div><div><dt>Dữ liệu hiện tại</dt><dd>Snapshot 132 kiện · cm/kg</dd></div><div><dt>Lưu trong bản mẫu</dt><dd>Phiên tab · chưa lưu bền</dd></div></dl><div class="m-account-notice"><strong>Đây chưa phải app vận hành</strong><p>Đăng nhập, nhận chuyến và gửi lại là mô phỏng. Ảnh xe cố định; sơ đồ vị trí đọc dữ liệu snapshot. Camera, backend và queue lưu bền chưa tích hợp.</p></div><a class="m-button secondary" href="./mobile-board.html">Mở toàn bộ bảng thiết kế</a><p class="m-source">Không nhập thông tin hoặc ảnh nhạy cảm vào bản duyệt.</p></div>`,'',{back:'settings'});
}

export function profile(){
 const pending=readQueue().filter(q=>q.status!=='sent').length;
 $('mobile-root').innerHTML=shell('profile',`<div class="m-content"><div class="m-profile"><span>${role==='driver'?'QD':'VH'}</span><h2>${role==='driver'?'Phạm Quốc Dũng':'Lê Văn Hải'}</h2><p>${role==='driver'?'Tài xế':'Nhân viên kho'} · Kho Long Bình</p>${tag('Tài khoản mẫu')}</div><div class="m-account-identity"><span>Email công việc</span><strong>${role==='driver'?'taixe':'kho'}@loadmaster.vn</strong></div><a class="m-link-row" href="${link('settings')}">${icon('layers')}<span>Cài đặt ứng dụng<small>Hiển thị, chuyển động, camera & ảnh</small></span>${icon('right')}</a><a class="m-link-row" href="${link('queue')}">${icon('sync')}<span>Thao tác chờ gửi<small>${pending} mục chưa gửi trong bản mẫu</small></span>${icon('right')}</a><a class="m-link-row" href="${link('access')}">${icon('user')}<span>Hỗ trợ tài khoản</span>${icon('right')}</a><button id="logout-open" class="m-button secondary">Đăng xuất bản mẫu</button><details class="m-demo-access"><summary>Công cụ duyệt thiết kế</summary><p>Đặt lại nhận chuyến và xác nhận kiện; giữ sự cố mẫu.</p><button id="reset-flow-open" class="m-button secondary">Thử lại luồng nhận chuyến</button></details><p class="m-source">Vai trò đổi ở thanh duyệt chỉ để xem thiết kế; không phải cơ chế phân quyền thật.</p></div>`,'',{nav:true})+sheet('logout-sheet',pending?'Còn thao tác chưa gửi':'Đăng xuất bản mẫu?',`<p class="m-source">${pending?`Có ${pending} mục chưa gửi. Nội dung vẫn giữ trong tab; đóng tab có thể mất dữ liệu mẫu.`:'Bạn sẽ quay về màn đăng nhập. Cài đặt hiển thị vẫn được giữ trong tab.'}</p>${pending?button('Xem hàng đợi trước','queue',true):''}<button id="logout-save" class="m-button ${pending?'secondary':'primary'}">${pending?'Vẫn đăng xuất bản mẫu':'Đăng xuất'}</button>`)+sheet('reset-flow-sheet','Đặt lại phiên thử?',`<p class="m-source">Xoá trạng thái nhận chuyến, xác nhận kiện và các mục xác nhận mẫu trong hàng đợi. Sự cố mẫu vẫn được giữ.</p><button class="m-button primary" id="reset-flow-save">Đặt lại luồng mẫu</button>`);
 $('logout-open').onclick=()=>$('logout-sheet').showModal();$('logout-save').onclick=()=>{sessionStorage.removeItem('lm-mobile-demo-session');location.href=link('login');};
 $('reset-flow-open').onclick=()=>$('reset-flow-sheet').showModal();$('reset-flow-save').onclick=()=>{resetFlow();location.href=link('home');};
}
