import { $,role,link,icon,button,tag,shell,sheet,readQueue } from './mobile-ui.js';
import { stops } from './trip-detail.mock.js';
import { flow,acceptTrip,doneCount } from './mobile-flow.js';
export function home(){
 const params=new URL(location.href).searchParams,state=params.get('state')??'ready',accepted=flow().accepted;
 const states={ready:'Có chuyến',empty:'Chưa có chuyến',loading:'Đang tải',error:'Không tải được',expired:'Hết phiên'};
 let content='';
 if(state==='loading')content='<div class="m-loading" role="status"><span class="m-skeleton"></span><span class="m-skeleton"></span><span class="m-skeleton"></span><p>Đang tải công việc…</p></div>'+button('Kết thúc cảnh tải mẫu','home');
 else if(state==='empty')content=`<div class="m-state-panel">${icon('truck')}<h2>Chưa có chuyến được giao</h2><p>Chuyến mới sẽ xuất hiện tại đây khi được phân công.</p>${button('Xem cảnh có chuyến mẫu','home',true)}</div>`;
 else if(state==='error'||state==='expired')content=`<div class="m-state-panel">${icon(state==='error'?'sync':'user')}<h2>${state==='error'?'Chưa tải được công việc':'Phiên đăng nhập đã hết hạn'}</h2><p>${state==='error'?'Không thể lấy danh sách chuyến. Thử lại khi có kết nối.':'Đăng nhập lại để xem công việc. Hàng đợi mẫu trong tab vẫn được giữ.'}</p>${state==='error'?button('Thử lại · mô phỏng','home',true):button('Đăng nhập lại','login',true,'&expired=1')}${button('Xem thao tác chờ gửi','queue')}</div>`;
 else content=`<div class="m-greeting"><div><span>22 tháng 9 · Kho Long Bình</span><h2>${role==='driver'?'Công việc hôm nay':'Ca xếp hàng'}</h2></div><span class="m-day-count">01<small>chuyến mẫu</small></span></div><div class="m-work-label"><strong>${accepted?'Chuyến đã nhận':'Chuyến được phân công'}</strong><span>${role==='driver'?'Tài xế · Quốc Dũng':'Kho · Văn Hải'}</span></div><section class="m-trip-card"><div class="m-card-meta"><span class="mono">TRIP-2026-0914</span>${tag(accepted?'Đã nhận · mẫu':'Chờ nhận',accepted?'success':'info')}</div><h3>Q.7 <span>→</span> Biên Hoà</h3><p>Qua Thủ Dầu Một và Dĩ An</p><div class="m-route-ribbon" aria-label="Thứ tự 4 điểm giao">${stops.map((s,i)=>`<div><span class="stop-dot stop-${i+1}">${i+1}</span><small>${['Quận 7','Thủ Dầu Một','Dĩ An','Biên Hoà'][i]}</small></div>`).join('')}</div><div class="m-facts"><div><strong>132</strong><span>kiện hàng</span></div><div><strong>4</strong><span>điểm giao</span></div><div><strong>5.844</strong><span>kg</span></div></div><div class="m-assigned-vehicle">${icon('truck')}<span><strong>60C-446.32</strong><small>Hyundai HD210 · 9.500 kg</small></span>${tag('Đã duyệt')}</div>${accepted?button(role==='driver'?'Tiếp tục lịch trình':'Tiếp tục xếp hàng',role==='driver'?'stop':'scene',true):'<button class="m-button primary" id="accept-open">Nhận chuyến mẫu</button>'}</section><div class="m-next-task"><span class="m-number">${icon('box')}</span><div><strong>${accepted?'Đối chiếu theo từng kiện':'Sau khi nhận chuyến'}</strong><p>${accepted?`${doneCount()} / 132 kiện đã xác nhận trong phiên`:'Mở điểm giao, xem vị trí và kiểm mã trước khi xác nhận.'}</p></div></div><a class="m-link-row" href="${link('queue')}">${icon('sync')}<span>Thao tác chờ gửi<small>${readQueue().filter(q=>q.status!=='sent').length} mục trong phiên mẫu</small></span>${icon('right')}</a><p class="m-source">MOCK RESULT · Một chuyến từ snapshot. Nhận chuyến không tự xác nhận xe đã xuất phát hoặc hàng đã được xếp.</p>`;
 $('mobile-root').innerHTML=shell('home',`<div class="m-content">${content}</div>`,'',{nav:true})+sheet('accept-sheet','Nhận chuyến mẫu',`<div class="m-confirm-summary"><h3>Q.7 → Biên Hoà</h3><p>TRIP-2026-0914 · 60C-446.32</p><p>132 kiện · 4 điểm giao</p></div><p class="m-source">Thử nhận công việc trong phiên duyệt. Không thay đổi phân công hoặc trạng thái chuyến thật.</p><button id="accept-save" class="m-button primary">Nhận & mở ${role==='driver'?'lịch trình':'hướng dẫn xếp'}</button>`);
 const picker=document.createElement('select');picker.id='m-state-review';picker.setAttribute('aria-label','Cảnh duyệt công việc');picker.innerHTML=Object.entries(states).map(([value,label])=>`<option value="${value}">${label}</option>`).join('');picker.value=Object.hasOwn(states,state)?state:'ready';picker.onchange=()=>{location.href=link('home',`&state=${picker.value}`);};document.querySelector('.m-review').append(picker);
 if($('accept-open'))$('accept-open').onclick=()=>$('accept-sheet').showModal();
 $('accept-save').onclick=()=>{acceptTrip();location.href=link(role==='driver'?'stop':'scene');};
}

