import { screenNames } from './screens.mock.js';
import { activateShell } from './screen-ui.js';
import { tripList, createTrip, optimization, planner } from './screens-dispatch.js';
import { driver, warehouse, queue } from './screens-field.js';
import { cargo } from './desktop-cargo.js';
import { fleet, vehicle } from './desktop-fleet.js';
import { dashboard, compare } from './desktop-insights.js';
import { users, audit, profile } from './desktop-admin.js';
import { components } from './desktop-components.js';
const requested = new URL(location.href).searchParams.get('screen');
const screen = Object.hasOwn(screenNames, requested) ? requested : 'trips';
document.title = `LoadMaster V2 · ${screenNames[screen]}`;
document.body.classList.toggle('solid-desktop', sessionStorage.getItem('loadmaster-v2-solid') === '1');
({ trips: tripList, create: createTrip, optimize: optimization, planner, driver, warehouse, queue, cargo, fleet, vehicle, dashboard, compare, users, audit, profile, components })[screen]();
activateShell();
