import { packages, stops, addresses } from './trip-detail.mock.js';
import { $, fmt, escape, href, badge, mobileShell, dialog } from './screen-ui.js';
const queueKey = 'loadmaster-v2-design-queue';
function readQueue() { try { return JSON.parse(sessionStorage.getItem(queueKey) ?? '[]'); } catch { return []; } }
function writeQueue(items) { sessionStorage.setItem(queueKey, JSON.stringify(items)); }
function addQueue(note, stop, photos = []) { const items = readQueue(); items.push({ id: `DEMO-${Date.now()}`, note, stop, photos, status: 'pending' }); writeQueue(items); }

export function driver() {
  $('screen-root').innerHTML = mobileShell('driver', `<div class="phone-content"><div class="mobile-trip-meta"><span class="mono">TRIP-2026-0914</span>${badge('Bản hướng dẫn mẫu', 'info')}</div><section class="phone-focus"><label class="field">Điểm cần xem<select id="driver-stop">${stops.map((s, i) => `<option value="${i + 1}">Điểm ${i + 1} / 4 · ${s}</option>`).join('')}</select></label><div id="stop-focus"></div></section><div class="phone-shortcuts"><a class="button secondary" id="map-link" target="_blank" rel="noopener">Mở bản đồ ↗</a><a class="button secondary" href="/tai-xe/diem-giao?chuyen=TRIP-2026-0914">Vị trí hàng 3D ↗</a></div><section class="phone-section"><div class="section-heading"><h2>Đối chiếu hàng tại điểm</h2><span id="driver-count"></span></div><p class="quiet-note">Đánh dấu nhóm hàng đã kiểm tra. Chưa ghi nhận giao hàng.</p><div id="driver-cargo"></div></section><button class="incident-button" id="report-incident">Báo sự cố kèm ảnh <span>→</span></button><a class="queue-link" href="${href('queue')}">Hàng đợi mẫu <span id="queue-count">${readQueue().length} mục</span></a></div>`, '<button id="review-delivery" class="button primary">Kiểm tra trước khi xác nhận</button>') + dialog('delivery-review', 'Kiểm tra giao hàng', '<div id="delivery-review-body"></div><form method="dialog"><button class="button primary">Đóng bản xem trước</button></form>') + dialog('incident-dialog', 'Ghi nhận sự cố mẫu', '<form id="incident-form"><label class="field">Nội dung<textarea id="incident-note" required minlength="5" placeholder="Mô tả tình trạng kiện và cách xử lý…"></textarea></label><label class="field">Ảnh sự cố<input id="incident-photo" type="file" accept="image/*" multiple></label><p id="photo-summary" class="quiet-note"></p><p class="quiet-note">Bản mẫu chỉ lưu nội dung và tên file trong phiên; chưa lưu hoặc gửi ảnh.</p><button class="button primary">Lưu vào hàng đợi mẫu</button></form>');
  let selectedStop = 1; const checked = new Set();
  function render() { const group = packages.filter(p => p.stop === selectedStop); const count = group.reduce((n, p) => n + p.quantity, 0); $('stop-focus').innerHTML = `<span class="stop-dot stop-${selectedStop}">${selectedStop}</span><h1>${stops[selectedStop - 1]}</h1><p>${addresses[selectedStop - 1]}</p><div class="phone-focus-numbers"><strong>${count} <span>kiện</span></strong><strong>${fmt.format(group.reduce((n, p) => n + p.kg * p.quantity, 0))} <span>kg</span></strong></div>`; $('map-link').href = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stops[selectedStop - 1] + ', ' + addresses[selectedStop - 1])}`; $('driver-cargo').innerHTML = group.map(p => `<label class="mobile-cargo-row"><input type="checkbox" value="${p.id}" ${checked.has(p.id) ? 'checked' : ''}><span><strong>${p.name}</strong><small>${p.id} · ${p.quantity} kiện · ${fmt.format(p.kg)} kg/kiện</small>${p.fragile ? badge('Dễ vỡ', 'warning') : badge(p.upright ? 'Giữ đứng' : 'Được xoay')}</span></label>`).join(''); $('driver-count').textContent = `${group.filter(p => checked.has(p.id)).length} / ${group.length} nhóm`; }
  $('driver-stop').onchange = e => { selectedStop = Number(e.target.value); render(); };
  $('driver-cargo').onchange = e => { if (e.target.checked) checked.add(e.target.value); else checked.delete(e.target.value); const group = packages.filter(p => p.stop === selectedStop); $('driver-count').textContent = `${group.filter(p => checked.has(p.id)).length} / ${group.length} nhóm`; };
  $('review-delivery').onclick = () => { const group = packages.filter(p => p.stop === selectedStop); const complete = group.every(p => checked.has(p.id)); $('delivery-review-body').innerHTML = `<h3>Điểm ${selectedStop} · ${stops[selectedStop - 1]}</h3><p>${complete ? 'Đã đối chiếu các nhóm hàng tại điểm này trong bản mẫu.' : 'Còn nhóm hàng chưa được đánh dấu đối chiếu.'}</p><p class="quiet-note">Đây là phác thảo bước xác nhận. Chưa cập nhật trạng thái giao trên hệ thống.</p>`; $('delivery-review').showModal(); };
  $('report-incident').onclick = () => $('incident-dialog').showModal();
  $('incident-photo').onchange = e => { $('photo-summary').textContent = [...e.target.files].map(f => f.name).join(', '); };
  $('incident-form').onsubmit = e => { e.preventDefault(); addQueue($('incident-note').value, `Điểm ${selectedStop} · ${stops[selectedStop - 1]}`, [...$('incident-photo').files].map(f => f.name)); $('queue-count').textContent = `${readQueue().length} mục`; $('incident-dialog').close(); e.target.reset(); $('photo-summary').textContent = ''; $('report-incident').focus(); };
  render();
}

export function warehouse() {
  $('screen-root').innerHTML = mobileShell('warehouse', `<div class="phone-content"><div class="mobile-trip-meta"><span class="mono">TRIP-011</span>${badge('MOCK RESULT', 'mock')}</div><div class="warehouse-progress"><span>Kiện cần xếp</span><strong>111 <small>/ 280</small></strong><progress value="110" max="280" aria-label="110 bước đã ghi nhận trên ảnh nguồn"></progress><small>Snapshot từ phiên kho hiện tại</small></div><section class="phone-focus warehouse-focus"><span class="mono warehouse-id">PKG-003-48</span><h1>Kiện nước giặt 4 can</h1>${badge('Điểm 3 · Lotte Mart Quận 7', 'info')}<div class="warehouse-directions"><div><span>Vị trí</span><strong>Lớp 3 · Cách cửa 570 cm</strong></div><div><span>Hướng đặt</span><strong>Đứng thẳng · Cạnh dài dọc thùng</strong></div><div><span>Khối lượng</span><strong>16 kg</strong></div></div></section><details class="warehouse-scene"><summary>Xem ảnh hướng dẫn vị trí</summary><img src="/docs/screenshots/handoff/vi-warehouse-tablet.png" alt="Ảnh nguồn phiên kho, kiện PKG-003-48 ở bước 111"><a href="/kho?chuyen=TRIP-011">Mở viewer kho hiện tại ↗</a></details><form id="scan-form" class="scan-form"><label class="field">Đối chiếu mã kiện<input id="scan-code" autocomplete="off" placeholder="Quét bằng máy hoặc nhập mã kiện" aria-describedby="scan-result"></label><div><button class="button secondary" type="button" id="sample-code">Điền mã mẫu</button><button class="button secondary">Kiểm tra mã</button></div><p id="scan-result" role="status"></p></form><p class="quiet-note">Ô nhập nhận máy quét dạng bàn phím. Quét bằng camera chưa triển khai trong prototype.</p></div>`, '<button class="button primary" id="warehouse-review">Kiểm tra trước khi xếp</button>') + dialog('warehouse-confirm', 'Đối chiếu trước khi xác nhận', '<p><strong>PKG-003-48 · Kiện nước giặt 4 can</strong></p><ul class="plain-checklist"><li>Đúng mã kiện và điểm giao 3.</li><li>Đúng hướng đặt, lớp và vị trí.</li><li>Không bỏ sót bước trước.</li></ul><p class="quiet-note">Chưa xác nhận bước xếp trong hệ thống. Thao tác thật thực hiện ở màn kho hiện tại.</p><a class="button primary" href="/kho?chuyen=TRIP-011">Mở phiên xếp hiện tại ↗</a>');
  $('sample-code').onclick = () => { $('scan-code').value = 'PKG-003-48'; $('scan-code').focus(); };
  $('scan-form').onsubmit = e => { e.preventDefault(); const match = $('scan-code').value.trim().toUpperCase() === 'PKG-003-48'; $('scan-result').textContent = match ? 'Mã khớp kiện cần xếp. Tiếp tục đối chiếu vị trí.' : 'Mã chưa khớp. Kiện đang cần xếp là PKG-003-48.'; $('scan-result').className = match ? 'scan-valid' : 'scan-error'; $('scan-code').setAttribute('aria-invalid', String(!match)); };
  $('warehouse-review').onclick = () => $('warehouse-confirm').showModal();
}

export function queue() {
  $('screen-root').innerHTML = mobileShell('queue', `<div class="phone-content"><section class="phone-focus"><span class="suite-caption">Hàng đợi trong phiên mẫu</span><h1>Thao tác chờ gửi</h1><p>Nội dung đã nhập được giữ trong tab này. Chưa kết nối máy chủ.</p></section><label class="queue-scenario">Tình huống thử<select id="queue-scenario"><option value="offline">Lỗi kết nối</option><option value="online">Gửi được (mô phỏng)</option></select></label><div id="queue-items" aria-live="polite"></div><button class="button secondary full-button" id="queue-sample">Thêm một sự cố mẫu</button><p class="quiet-note">Không phải offline-first. Ảnh mới chỉ lưu tên file; chưa có cơ chế gửi ảnh, idempotency hoặc xác nhận từ backend.</p></div>`, '<a class="button secondary" href="./screens.html?screen=driver">Quay lại điểm giao</a>');
  function render() { const items = readQueue(); $('queue-items').innerHTML = items.length ? items.map(item => `<article class="queue-card"><div>${badge(item.status === 'sent-demo' ? 'Mẫu: đã gửi' : item.status === 'failed' ? 'Chưa gửi được' : 'Chờ gửi', item.status === 'failed' ? 'warning' : item.status === 'sent-demo' ? 'success' : 'neutral')}<small>Sự cố tại điểm giao</small></div><h2>${escape(item.stop)}</h2><p>${escape(item.note)}</p><small>${item.photos.length ? `${item.photos.length} tên file ảnh · chưa lưu ảnh` : 'Không đính kèm ảnh'}</small>${item.status === 'failed' ? '<p class="scan-error">Mẫu lỗi kết nối. Nội dung vẫn được giữ để thử lại.</p>' : ''}<div class="queue-actions">${item.status !== 'sent-demo' ? `<button class="button secondary" data-retry="${item.id}">Thử gửi (mẫu)</button>` : ''}<button class="text-button" data-remove="${item.id}">Xoá mục mẫu</button></div></article>`).join('') : '<div class="queue-empty"><h2>Không có thao tác chờ gửi</h2><p>Sự cố lưu từ màn tài xế sẽ xuất hiện tại đây.</p></div>'; }
  $('queue-sample').onclick = () => { addQueue('Thùng ly thuỷ tinh móp góc, cần đối chiếu trước khi giao.', 'Điểm 2 · Co.opmart Bình Dương'); render(); };
  $('queue-items').onclick = e => { const retry = e.target.closest('[data-retry]'), remove = e.target.closest('[data-remove]'); if (!retry && !remove) return; let items = readQueue(); if (retry) items = items.map(item => item.id === retry.dataset.retry ? { ...item, status: $('queue-scenario').value === 'online' ? 'sent-demo' : 'failed' } : item); else items = items.filter(item => item.id !== remove.dataset.remove); writeQueue(items); render(); };
  render();
}
