import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
const base = 'http://127.0.0.1:5182/design/v2/';
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
  const errors = [];
  await page.emulateMedia({ reducedMotion: 'reduce' });
  page.on('pageerror', e => errors.push(e.message));
  const go = async screen => { await page.goto(`${base}screens.html?screen=${screen}`); await page.evaluate(() => document.fonts.ready); };
  for (const screen of ['trips', 'create', 'optimize', 'planner', 'driver', 'warehouse', 'queue']) {
    await go(screen);
    assert.ok(await page.locator('h1').count());
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, screen);
    assert.equal(await page.locator('img').evaluateAll(imgs => imgs.some(img => !img.complete || !img.naturalWidth)), false, screen);
    await page.screenshot({ path: `design/v2/screen-${screen}.png`, fullPage: true });
  }
  await go('trips');
  await page.locator('#trip-search').fill('bien hoa');
  assert.equal(await page.locator('#trip-rows tr').count(), 3);
  await page.locator('#trip-search').fill('');
  await page.locator('#attention-filter').click();
  assert.equal(await page.locator('#trip-rows tr').count(), 2);
  await page.locator('[data-trip="TRIP-013"]').click();
  assert.equal(await page.locator('#trip-preview').evaluate(d => d.open), true);
  await page.keyboard.press('Escape');
  await go('create');
  await page.locator('[name=name]').fill('Chuyến kiểm tra <b>');
  await page.locator('#vehicle-choice').selectOption('Isuzu NQR 550');
  await page.getByRole('button', { name: 'Xem lại bản nháp' }).click();
  assert.equal(await page.locator('#draft-review').evaluate(d => d.open), false);
  await page.locator('#vehicle-choice').selectOption('Hyundai HD210');
  await page.locator('[data-move="0,1"]').click();
  await page.getByRole('button', { name: 'Xem lại bản nháp' }).click();
  assert.equal(await page.locator('#draft-review-body h3').textContent(), 'Chuyến kiểm tra <b>');
  assert.match(await page.locator('#draft-review-body li').first().textContent(), /Co.opmart/);
  await go('optimize');
  await page.getByRole('button', { name: 'Xem bước chạy mẫu' }).click();
  assert.equal(await page.locator('#run-preview').evaluate(d => d.open), true);
  await go('planner');
  await page.locator('#planner-package').selectOption('PKG-003');
  assert.match(await page.locator('#planner-package-detail').textContent(), /30 kg/);
  await page.locator('[data-panel=review]').click();
  assert.match(await page.locator('#planner-content').textContent(), /Trước khi duyệt/);
  await page.setViewportSize({ width: 390, height: 844 });
  for (const screen of ['driver', 'warehouse', 'queue']) {
    await go(screen);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `phone ${screen}`);
    await page.screenshot({ path: `design/v2/screen-${screen}-phone.png`, fullPage: true });
  }
  await go('driver');
  await page.locator('#driver-stop').selectOption('2');
  assert.equal(await page.locator('#driver-cargo input').count(), 2);
  await page.locator('#report-incident').click();
  await page.locator('#incident-note').fill('Kiện thuỷ tinh bị móp góc');
  await page.locator('#incident-photo').setInputFiles({ name: 'su-co.png', mimeType: 'image/png', buffer: Buffer.from('mock') });
  await page.getByRole('button', { name: 'Lưu vào hàng đợi mẫu' }).click();
  await go('queue');
  assert.equal(await page.locator('.queue-card').count(), 1);
  await page.locator('[data-retry]').click();
  assert.match(await page.locator('.queue-card').textContent(), /Chưa gửi được/);
  await page.locator('#queue-scenario').selectOption('online');
  await page.locator('[data-retry]').click();
  assert.match(await page.locator('.queue-card').textContent(), /Mẫu: đã gửi/);
  await page.screenshot({ path: 'design/v2/screen-queue-populated.png', fullPage: true });
  await page.locator('[data-remove]').click();
  assert.equal(await page.locator('.queue-card').count(), 0);
  await go('warehouse');
  await page.locator('#scan-code').fill('WRONG');
  await page.getByRole('button', { name: 'Kiểm tra mã', exact: true }).click();
  assert.equal(await page.locator('#scan-code').getAttribute('aria-invalid'), 'true');
  await page.locator('#sample-code').click();
  await page.getByRole('button', { name: 'Kiểm tra mã', exact: true }).click();
  assert.equal(await page.locator('#scan-code').getAttribute('aria-invalid'), 'false');
  assert.deepEqual(errors, []);
  console.log('7 screens: render, desktop/phone overflow, filters, draft validation, reorder, planner panel, incident queue, scan all pass.');
} finally { await browser.close(); }
